openapi: 3.0.0
info:
  title: API
  version: v1
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/PetByAge'
                - $ref: '#/components/schemas/PetByType'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/PetByAge'
                  - $ref: '#/components/schemas/PetByType'
components:
  schemas:
    PetByAge:
      type: object
      properties:
        age:
          type: integer
        nickname:
          type: string
      required:
        - age

    PetByType:
      type: object
      properties:
        pet_type:
          type: string
          enum: [Cat, Dog]
        hunts:
          type: boolean
      required:
        - pet_type
    TimeLineList:
      type: object
      properties:
        results:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/PetByType'
              - $ref: '#/components/schemas/PetByAge'