openapi: 3.0.0
info:
  title: API
  version: v1
tags:
  - name: profile
    description: Профиль пользователя
paths:
  '/profile/{user_id}/{unit_id}/activity/':
    post:
      operationId: profile_activity_create
      requestBody:
        $ref: '#/components/requestBodies/UnitActivitySet'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UnitActivity'
        '400':
          $ref: '#/components/responses/ValidationError'
      tags:
        - profile
    parameters:
      - $ref: '#/components/parameters/userIdParam'
      - $ref: '#/components/parameters/unitIdParam'
  '/profile/notification/':
    get:
      operationId: profile_notification
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserNotification'
        '400':
          $ref: '#/components/responses/ValidationError'
      tags:
        - profile
  '/profile/info/enumarray':
    get:
      operationId: profile_info_enumarray
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfoWithArray'
        '400':
          $ref: '#/components/responses/ValidationError'
      tags:
        - profile
  '/profile/info/state':
    get:
      operationId: profile_info_state
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserStateEnum'
        '400':
          $ref: '#/components/responses/ValidationError'
      tags:
        - profile
  /profile/user/settings/:
    post:
      description: Сохранить настройки пользователя
      operationId: profile_user_settings_create
      requestBody:
        content:
          application/json:
            schema:
              description: Настройки видимости
              properties:
                settings:
                  $ref: "#/components/schemas/UserSettingsNullableSchema"
              required:
                - settings
              type: object
        required: true
      responses:
        "201":
          description: Успешное создание
        "400":
          $ref: "#/components/responses/ValidationError"
  '/profile/info/state/{id}/':
    put:
      tags:
        - profile
      parameters:
        - schema:
            type: string
            nullable: true
          name: id
          in: path
          required: true
          description: id
      requestBody:
        $ref: '#/components/requestBodies/UserInfoBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserStateEnum'
  '/profile/{user_id}/{unit_id}/activity2/':
    post:
      operationId: profile_activity_create2
      requestBody:
        $ref: '#/components/requestBodies/UnitActivityArray2'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UnitActivity'
        '400':
          $ref: '#/components/responses/ValidationError'
      tags:
        - profile
    parameters:
      - $ref: '#/components/parameters/userIdParam'
      - $ref: '#/components/parameters/unitIdParam'
  '/profile/get/map':
    get:
      operationId: api_profile_get_map
      description: Получить хэшмапу
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfoWithMap'
  '/profile/get/set':
    get:
      operationId: api_profile_get_set
      description: Получить множество
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfoWithSet'
security:
  - Bearer: []
components:
  securitySchemes:
    Bearer:
      in: header
      name: Authorization
      type: apiKey
  requestBodies:
    Car:
      content:
        application/json:
          schema:
            type: object
            properties:
              car_number:
                minLength: 1
                title: Car number
                type: string
                nullable: true
              car_rid:
                format: uuid
                title: Car rid
                type: string
              car_pid:
                format: uuid
                title: Car rid
                type: string
                nullable: false
              car_sid:
                format: uuid
                title: Car rid
                type: string
            required:
              - car_number
              - car_rid
              - car_pid
      required: true
    UserInfoBody:
      required: false
      content:
        application/json:
          schema:
            nullable: true
            $ref: '#/components/schemas/UserSettingsNullableSchema'
    UnitActivitySet:
      content:
        application/json:
          schema:
            type: array
            uniqueItems: true
            items:
              type: object
              properties:
                is_main_activity:
                  type: boolean
                activity_rid:
                  title: Основное направление
                  type: string
                  format: uuid
                functional_activity_rid:
                  title: Функциональное направление
                  type: string
                  format: uuid
    UnitActivityArray2:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/UnitActivityArray2Item'
  responses:
    ValidationError:
      description: Validation Error
      content:
        application/json:
          schema:
            description: Ошибка валидации
            properties:
              detail:
                description: Описание ошибки
                type: string
            type: object
  parameters:
    userIdParam:
      in: path
      name: user_id
      required: true
      schema:
        type: string
        format: uuid
      example: e0520e34-01b3-4ddb-b08a-2735a7dfde56
      description: 'Идентификатор пользователя из keycloak'
    unitIdParam:
      in: path
      name: unit_id
      required: true
      schema:
        type: integer
        minimum: 1
      description: 'Идентификатор модели оргструктуры'
  schemas:
    Unit:
      type: object
      properties:
        name:
          maxLength: 255
          minLength: 1
          title: Название
          type: string
        name_rid:
          format: uuid
          type: string
          description: UUID из сервиса справочников
        division:
          maxLength: 255
          minLength: 1
          title: Дивизион
          type: string
        organization:
          maxLength: 255
          minLength: 1
          title: Организация
          type: string
        organization_unit:
          maxLength: 255
          minLength: 1
          title: Организацинная еденица
          type: string
        position:
          maxLength: 255
          minLength: 1
          title: Должность
          type: string
        user:
          format: uuid
          title: Сотрудник
          type: string
          nullable: true
        work_town:
          description: Город работы
          minLength: 1
          title: Work town
          type: string
          nullable: true
        activities:
          type: array
          items:
            $ref: '#/components/schemas/UnitActivity'
        employee_number:
          type: string
          description: Табельный номер
        remote_employee:
          type: boolean
          description: Внешний сотрудник
          default: false
        organization_rid:
          type: string
          format: uuid
          description: UUID из сервиса справочников
        organization_unit_rid:
          type: string
          format: uuid
          description: UUID из сервиса справочников
        division_rid:
          type: string
          format: uuid
          description: UUID из сервиса справочников
        position_rid:
          type: string
          format: uuid
          description: UUID из сервиса справочников
      required:
        - division
        - organization
        - organization_unit
        - position
    UnitActivity:
      title: UnitActivity
      type: object
      properties:
        id:
          type: string
          format: uuid
        is_main_activity:
          type: boolean
        activity:
          type: string
        functional_activity:
          type: string
          nullable: true
        activity_rid:
          title: Основное направление
          type: string
          format: uuid
        functional_activity_rid:
          title: Функциональное направление
          type: string
          format: uuid
          nullable: true
    UnitActivityArray2Item:
      type: object
      properties:
        is_main_activity:
          type: boolean
        activity_rid:
          title: Основное направление
          type: string
          format: uuid
        functional_activity_rid:
          title: Функциональное направление
          type: string
          format: uuid
    UserNotification:
      type: object
      properties:
        id:
          title: ID
          type: integer
          readOnly: true
        content:
          type: object
        userInfo:
          oneOf:
            - $ref: "#/components/schemas/UserInfo"
            - description: Info
              type: string
    UserInfo:
      type: object
      properties:
        name:
          type: string
          readOnly: true
    UserInfoWithSet:
      type: object
      properties:
        values:
          type: array
          uniqueItems: true
          items:
            type: string
    UserInfoWithMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/UserInfo'
    UserInfoWithArray:
      type: object
      properties:
        values:
          type: array
          description: Activity categories list
          items:
            type: string
            enum:
              - OnQueueWork
              - Break
              - Meal
              - Meeting
              - OffQueueWork
              - TimeOff
              - Training
              - Unavailable
              - Unscheduled
    UserStateEnum:
      type: object
      properties:
        state_name:
          title: Состояние
          type: string
          enum:
            - null
            - state_1
            - state_2
          nullable: true
    DecimalTest:
      type: object
      properties:
        amount:
          title: Amount
          type: string
          format: number
        total:
          title: Total
          type: string
          format: decimal
    UserSettingsNullableSchema:
      properties:
        about_me_required_nullable:
          description: Обязательное нуллабельное значение
          type: string
          nullable: true
        raiting_required_nonnull:
          description: Обязательное не нуллабельное значение
          maximum: 2
          minimum: 0
          type: integer
          nullable: false
        work_id_nonrequired_nullable:
          description: Необязательное нуллабельное значение без дефолта
          type: integer
          nullable: true
        array_nonrequired_nullable:
          description: Необязательный нуллабельный массив
          type: array
          items:
            type: string
          nullable: true
        office_nonrequired_nonnull:
          description: Необязательное не нуллабельное значение с дефолтом
          type: integer
          nullable: false
          default: 0
        office_nonrequired_nonnull_without_default:
          description: Необязательное не нуллабельное значение без дефолта
          type: string
          nullable: false
      required:
        - about_me_required_nullable
        - raiting_required_nonnull
      type: object
